### ISSUE TITLE
Uncaught exception 'InvalidArgumentException' with message 'Identifier "security.authentication_providers" is not defined.

### ISSUE THREAD

**Issue by Sorien** [silexphp/Silex-WebProfiler#5]
after registring WebProfilerServiceProvider im getting this error

```
    <b>Fatal error</b>:  Uncaught exception 'InvalidArgumentException' with message 'Identifier &quot;security.authentication_providers&quot; is not defined.' in D:\private\www\cms\vendor\pimple\pimple\lib\Pimple.php:78
    Stack trace:
    #0 D:\private\www\cms\vendor\silex\silex\src\Silex\Provider\SecurityServiceProvider.php(78): Pimple-&gt;offsetGet('security.authen...')
    #1 D:\private\www\cms\vendor\pimple\pimple\lib\Pimple.php(122): Silex\Provider\SecurityServiceProvider-&gt;Silex\Provider\{closure}(Object(Sorien\Application))
    #2 D:\private\www\cms\vendor\pimple\pimple\lib\Pimple.php(83): Pimple-&gt;{closure}(Object(Sorien\Application))
    #3 D:\private\www\cms\vendor\silex\silex\src\Silex\Provider\SecurityServiceProvider.php(74): Pimple-&gt;offsetGet('security.authen...')
    #4 D:\private\www\cms\vendor\pimple\pimple\lib\Pimple.php(122): Silex\Provider\SecurityServiceProvider-&gt;Silex\Provider\{closure}(Object(Sorien\Application))
    #5 D:\private\www\cms\vendor\pimple\pimple\lib\Pimple.php(83): Pimple-&gt;{closure}(Object(Sorien\Application))
    #6 D:\private\www\cms\vendor in <b>D:\private\www\cms\vendor\pimple\pimple\lib\Pimple.php</b> on line <b>78</b><br />
```

config: 
https://gist.github.com/Sorien/4737951

full error from xdebug:
https://gist.github.com/Sorien/4737954

there is problem when i register SecurityServiceProvider and WebProfilerServiceProvider together

**Comment by tsantos84** [comment]
Just to let you know. Even this thread is quite old, I've faced this problem with a fresh installation of `Silex, WebProfilerServiceProvider and SecurityServiceProvider`. What we need to do is to register `SecurityServiceProvider` before `WebProfilerServiceProvider` to avoid that `InvalidArgumentException.`
